# 45 프로미스

## 45.1 비동기 처리를 위한 콜백 패턴의 단점

### 45.1.1

#### 💻 예제 코드 1

<br>

```javascript
// GET 요청을 위한 비동기 함수
const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // 서버의 응답을 콘솔에 출력한다.
      console.log(JSON.parse(xhr.response));
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

// id가 1인 post를 취득
get('https://jsonplaceholder.typicode.com/posts/1');
/*
{
  "userId" : 1,
  "id" : 1,
  "title": "sunt aut facere ...",
  "body": "quia et suscipit ..."
}
*/
```

<br>

위의 예제 코드에서 정의된 `get` 함수는 비동기 함수다. 비동기 함수란, 함수 내부에 비동기로 동작하는 코드를 포함하는 함수를 말한다. 비동기 함수를 호출하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않았다 하더라도 기다리지 않고 즉시 종료된다. 즉, 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다. 따라서 비동기 함수 내부의 비동기로 동작하는 코드에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대와 다르게 동작한다.

또 다른 비동기 함수 예시로 `setTimeout`이 있다.

<br>

#### 💻 예제 코드 2

```javascript
let g = 0;

// 비동기 함수인 setTimeout 함수는 콜백 함수의 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하지 못한다.
setTimeout(() => {
  g = 100;
}, 0);
console.log(g); // 0
```

<br>

`setTimeout` 함수를 호출하면 콜백 함수를 호출 스케줄링한 다음, 타이머 id를 반환하고 즉시 종료된다. 즉, 비동기 함수인 `setTimeout` 함수의 콜백 함수는 `setTimeout` 함수가 종료된 이후에 호출된다. 따라서 `setTimeout` 함수 내부의 콜백 함수에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않는다.

<br>

다시 '예제 코드 1'로 돌아가서, GET 요청을 전송하고 서버의 응답을 전달받는 `get` 함수는 비동기 함수다. `get` 함수 내부의 `onload` 이벤트 핸들러가 비동기로 동작하기 때문이다. `get` 함수를 호출하면 GET 요청을 전송하고 `onload` 이벤트 핸들러를 등록한 다음 `undefined`를 반환하고 즉시 종료된다. 즉, 비동기 함수인 `get` 함수 내부의 `onload` 이벤트 핸들러는 `get` 함수가 종료된 이후 실행된다. 따라서 `get` 함수의 `onload` 이벤트도 '예제 코드 2'에서 봤듯이 서버의 응답 결과를 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않는다.

🤓 `get` 함수가 서버의 응답 결과를 반환하도록 수정해 보자!

<br>

#### 💻 예제 코드 3

<br>

```javascript
// GET 요청을 위한 비동기 함수
const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // ① 서버의 응답을 반환한다.
      return JSON.parse(xhr.response);
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

// ② id가 1인 post를 취득
const reponse = get('https://jsonplaceholder.typicode.com/posts/1');
console.log(response); // undefined
```

<br>

'예제 코드 1'과 마찬가지로 `get` 함수가 호출되면 `XMLHttpRequest` 객체를 생성하고, HTTP 요청을 초기화한 후, HTTP 요청을 전송한다. 그리고 `xhr.onload` 이벤트 핸들러 프로퍼티에 이벤트 핸들러를 바인딩하고 종료한다. 이때 `get` 함수에 명시적인 반환문이 없으므로 `get` 함수는 `undefined`를 반환한다.(②)

`xhr.onload` 이벤트 핸들러 프로퍼티에 바인딩한 이벤트 핸들러의 반환문(①)은 `get` 함수의 반환문이 아니다. 함수의 반환값은 명시적으로 호출한 다음에 캐치할 수 있으므로 `onload` 이벤트 핸들러를 `get` 함수가 호출할 수 있다면 이벤트 핸들러의 반환값을 `get` 함수가 캐치하여 다시 반환할 수 있겠지만 `onload` 이벤트 핸들러는 `get` 함수가 호출하지 않기 때문에 그 반환값을 캐치할 수 없다.

그렇다면 ①에서 아래와 같이 서버의 응답을 상위 스코프의 변수에 할당하면 어떨까?

#### 💻 예제 코드 4

<br>

```javascript
let todos;

// GET 요청을 위한 비동기 함수
const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // ① 서버의 응답을 상위 스코프의 변수에 할당한다.
      todos = JSON.parse(xhr.response);
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

// ② id가 1인 post를 취득
const reponse = get('https://jsonplaceholder.typicode.com/posts/1');
console.log(response); // undefined
```

<br>

이 또한 기대한대로 동작하지는 않는다. **`xhr.onload` 이벤트 핸들러 프로퍼티에 바인딩된 이벤트 핸들러는 언제나 ②의 `console.log`가 종료한 이후에 호출된다.** 따라서 ②의 시점에는 아직 전역 변수 todos에 서버의 응답 결과가 할당되기 이전이므로 `xhr.onload` 이벤트 핸들러에서 서버의 응답을 상위 스코프의 변수에 할당(①)하면 처리 순서가 보장되지 않는다.

비동기 함수 **`get`이 호출되면** 함수 코드를 평가하는 과정에서 `get` 함수의 실행 컨텍스트가 생성되고 실행 컨텍스트 스택(콜 스택)에 푸시된다. 이후 함수 코드 실행 과정에서 **`xhr.onload` 이벤트 핸들러 프로퍼티에 이벤트 핸들러가 바인딩된다.**

**`get` 함수가 종료하면** `get` 함수의 실행 컨텍스트가 콜 스택에서 팝되고, 곧바로 **②의 `console.log`가 호출된다.** 이때 `console.log`의 실행 컨텍스트가 생성되어 실행 컨텍스트 스택에 푸시된다. **만약 `console.log`가 호출되기 직전에 `load` 이벤트가 발생했더라도 `xhr.onload` 이벤트 핸들러 프로퍼티에 바인딩한 이벤트 핸들러는 결코 `console.log`보다 먼저 실행되지 않는다.**

서버로부터 응답이 도착하면 `xhr` 객체에서 `load` 이벤트가 발생한다. 이때 **`xhr.onload` 핸들러 프로퍼티에 바인딩한 이벤트 핸들러가 즉시 실행되는 것이 아니고 `xhr.onload` 이벤트 핸들러는 `load` 이벤트가 발생하면 일단 태스크 큐에 저장되어 대기하다가, 콜 스택이 비면 이벤트 루프에 의해 콜 스택으로 푸시되어 실행된다.**

따라서 `xhr.onload` 이벤트 핸들러가 실행되는 시점에는 콜 스택이 빈 상태여야 하므로 ②의 `console.log`는 이미 종료된 이후다. 즉, 항상 `xhr.onload`이벤트 핸들러에서 상위 스코프의 변수에 서버의 응답 결과를 할당하기 이전에 `console.log`가 먼저 호출되어 `undefined`를 출력하는 것이다.

**이처럼 비동기 함수는 비동기 처리 결과를 외부에 반환할 수 없고, 상위 스코프의 변수에 할당할 수도 없다.(꺼내서 지지고 볶고 할 수 없다!) 따라서 비동기 함수의 처리 결과(서버의 응답 등)에 대한 후속 처리는 비동기 함수 내부에서 수행해야 한다. **

이때 비동기 함수를 범용적으로 사용하기 위해 **비동기 함수에 비동기 처리 결과에 대한 후속 처리를 수행하는 콜백 함수를 전달하는 것이 일반적**이다. 필요에 따라 **비동기 처리가 성공하면 호출될 콜백 함수**와 **비동기 처리가 실패하면 호출될 콜백 함수를 전달**할 수 있다.

<br>

#### 💻 예제 코드 5

<br>

```javascript
// GET 요청을 위한 비동기 함수
const get = (url, successCallback, failureCallback) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // 서버의 응답을 콜백 함수에 인수로 전달하면서 호출하여 응답에 대한 후속 처리를 한다.
      successCallback(JSON.parse(xhr.response));
    } else {
      // 에러 정보를 콜백 함수에 인수로 전달하면서 호출하여 에러 처리를 한다.
      failurecallback(xhr.status);
    }
  };
};

// id가 1인 post를 취득
// 서버의 응답에 대한 후속 처리를 위한 콜백 함수를 비동기 함수인 get에 전달해야 한다.
get('https://jsonplaceholder.typicode.com/posts/1', console.log, console.error);
```

<br>

이처럼 콜백 함수를 통해 비동기 처리 결과에 대한 후속 처리를 수행하는 비동기 함수가 비동기 처리 결과를 가지고 또다시 비동기 함수를 호출해야 한다면 콜백 함수 호출이 중첩되어 복잡도가 높아지는 현상이 발생하는데, 이를 **콜백 지옥, 콜백 헬(callback hell)**이라 한다. 아래의 예제를 보자.

<br>

#### 💻 예제 코드 6

<br>

```javascript
// GET 요청을 위한 비동기 함수
const get = (url, callback) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // 서버의 응답을 콜백 함수에 인수로 전달하면서 호출하여 응답에 대한 후속 처리를 한다.
      callback(JSON.parse(xhr.response));
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

const url = 'https://jsonplaceholder.typicode.com';

// id가 1인 post의 userId를 취득
get(`${url}/posts/1`, ({ userId }) => {
  console.log(userId); // 1
  // post의 userId를 사용하여 user 정보를 취득
  get(`${url}/posts/${userId}`, (userInfo) => {
    console.log(userInfo); // {id: 1, name: "Leanne Graham", username: "Bret", ... }
  });
});
```

<br>

위 예제처럼 응답 데이터를 가지고 또 데이터 요청을 하는 콜백 헬은 가독성을 나쁘게 하며 실수를 유발하는 원인이 되기도 한다.

<br>

### 45.1.2 에러 처리의 한계

비동기 처리를 위한 콜백 패턴의 가장 큰 문제는 에러 처리가 곤란하다는 것이다. 다음 예제를 살펴보자.

<br>

#### 💻 예제 코드 7

<br>

```javascript
try {
  setTimeout(() > { throw new Error('Error!'); }, 1000);
} catch (e) {
  // 에러를 캐치하지 못한다
  console.error('캐치한 에러', e);
}
```

<br>

`try` 코드 블록 내에서 호출한 `setTimeout` 함수는 1초 후에 콜백 함수가 실행되도록 타이머를 설정하고, 이후 콜백 함수는 에러를 발생시킨다. 하지만 이 에러는 `catch` 코드 블록에서 캐치되지 않는다.

비동기 함수인 `setTimeout`이 호출되면 콜 스택에 푸시되어 실행되고 콜백 함수가 호출되는 것을 기다리지 않고 즉시 종료되어 콜 스택에서 제거된다. 이후 타이머가 만료되면 `setTimeout` 함수의 콜백 함수는 태스크 큐로 푸시되고 콜 스택이 비어졌을 때 이벤트 루프에 의해 콜 스택으로 푸시되어 실행될 것이다.

`setTimeout` 함수의 콜백 함수가 실행될 때 `setTimeout` 함수는 이미 콜 스택에서 제거된 상태이다. 이것은 `setTimeout` 함수의 콜백 함수를 호출한 것이 `setTimeout` 함수가 아니라는 것을 의미한다. `setTimeout` 함수의 콜백 함수의 호출자가 `setTimeout` 함수라면 콜 스택의 현재 실행 중인 실행 컨텍스트가 콜백 함수의 실행 컨텍스트일 때 현재 실행 중인 실행 컨텍스트의 하위 실행 컨텍스트가 `setTimeout` 함수여야 한다.

**에러는 호출자 방향으로 전파된다.** 즉, 콜 스택의 아래 방향(실행 중인 실행 컨텍스트가 푸시되기 직전에 푸시된 실행 컨텍스트 방향)으로 전파된다. 하지만 `setTimeout` 함수의 콜백 함수를 호출한 것은 `setTimeout` 함수가 아니기 때문에 `setTimeout` 함수의 콜백 함수가 발생시킨 에러는 `catch` 블록에서 캐치되지 않는다.

🎨 이해를 돕기 위한 이미지([23장 실행 컨텍스트](https://velog.io/@wlals4264/23-%EC%8B%A4%ED%96%89-%EC%BB%A8%ED%85%8D%EC%8A%A4%ED%8A%B8))

![](https://velog.velcdn.com/images/wlals4264/post/2b1d7545-2423-42c0-a2e4-38503b4125e2/image.png)

이와 같이 비동기 처리를 위한 콜백 패턴은 콜백 헬이나 에러 처리가 곤란하다는 문제가 있고 이를 극복하기 위해 ES6에서 프로미스(Promise)가 도입되었다.

<br>

## 45.2 프로미스의 생성

`Promise` 생성자 함수를 `new` 연산자와 함께 호출하면 프로미스(`Promise` 객체)를 생성한다. `Promise`는 호스트 객체가 아닌 ES6에서 도입된 ECMAScript 사양에 정의된 표준 빌트인 객체다.

`Promise` 생성자 함수는 비동기 처리를 수행할 콜백 함수를 인수로 전달받는데 이 콜백 함수는 `resolve`와 `reject` 함수를 인수로 전달받는다.

<br>

#### 💻 프로미스 생성 예제

<br>

```javascript
// 프로미스 생성
const promise = new Promise((resolve, reject) => {
  // Promise 함수의 콜백 함수 내부에서 비동기 처리를 수행한다.
  if (/* 비동기 처리 성공 */) {
    resolve('result');
  } else { /* 비동기 처리 실패 */
    reject('failure reason');
  }
});
```

<br>

`Promise` 생성자 함수가 인수로 전달받은 콜백 함수 내부에서 비동기 처리를 수행한다. 이때 비동기 처리가 성공하면 콜백 함수의 인수로 전달받은 `resolve` 함수를 호출하고, 비동기 처리가 실패하면 `reject` 함수를 호출한다. 앞에서 살펴본 비동기 함수 `get`을 프로미스를 사용하여 구현해보자.

<br>

#### 💻 `get` 함수 리팩토링(Promise 사용)

<br>

```javascript
// GET 요청을 위한 비동기 함수
const promiseGet = (url) => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
        // 성공적으로 응답을 전달받으면 resolve 함수를 호출한다.
        resolve(JSON.parse(xhr.response));
      } else {
        // 에러 처리를 위해 reject 함수를 호출한다.
        reject(new Error(xhr.status));
      }
    };
  });
};

// promiseGet 함수는 프로미스를 반환한다.
promiseGet('https://jsonplaceholder.typicode.com/posts/1');
```

<br>

비동기 함수인 `promiseGet` 함수 내부에서 프로미스를 생성하고 반환한다. 비동기 처리는 `Promise` 생성자 함수가 인수로 전달받은 콜백 함수 내부에서 수행한다. 만약 비동기 처리가 성공하면 비동기 처리 결과를 `resolve` 함수에 인수로 전달하면서 호출하고, 비동기 처리가 실패하면 에러를 `reject` 함수에 인수로 전달하면서 호출한다.

<br>

프로미스는 다음과 같이 현재 비동기 처리가 어떻게 진행되고 있는지 나타내는 상태 정보를 갖는다.

<br>

![](https://velog.velcdn.com/images/wlals4264/post/b8905d1f-7a28-4716-8407-91673c2d1b1d/image.png)

<br>

생성된 직후의 프로미스는 기본적으로 `pending` 상태다. 이후 비동기 처리가 수행되면 비동기 처리 결과에 따라 다음과 같이 프로미스의 상태가 변한다.

- 비동기 처리 성공: `resolve` 함수를 호출해 프로미스를 `fulfilled` 상태로 변경
- 비동기 처리 실패: `reject` 함수를 호출해 프로미스를 `rejected` 상태로 변경

이처럼 **프로미스의 상태는 `resolve` 또는 `reject` 함수를 호출하는 것으로 결정된다.**

<br>

![](https://velog.velcdn.com/images/wlals4264/post/e6307907-5974-4137-9f0a-4b2816860073/image.png)

<br>

`fulfilled` 또는 `rejected` 상태를 `settled` 상태라고 한다. `settled` 상태는 `fulfilled` 또는 `rejected` 상태와 상관없이 `pending`이 아닌 상태로 비동기 처리가 수행된 상태를 말한다.

프로미스는 `pending` 상태에서 `fulfilled` 또는 `rejected` 상태, 즉 `settled` 상태로 변화할 수 있다. 하지만 일단 `settled` 상태가 되면 더는 다른 상태로 변화할 수 없다.

프로미스는 비동기 처리 상태와 더불어 비동기 처리 결과(위 그림의 `result`)도 상태로 갖는다. 아래의 프로미스를 개발자 도구에서 출력해보자.

<br>

#### 💻 예제 코드 10 (✅ 성공!! resolve)

<br>

```javascript
// fulfilled된 프로미스
const fulfilled = new Promise((resolve) => resolve(1));
```

<br>

![](https://velog.velcdn.com/images/wlals4264/post/da67585a-83b7-473a-9340-44b937c588d4/image.png)

#### 💻 예제 코드 10 (❎ 실패!! reject)

<br>

```javascript
// rejected된 프로미스
const rejected = new Promise((_, reject) => reject(new Error('error occured')));
```

<br>

![](https://velog.velcdn.com/images/wlals4264/post/b9e91a48-b1e1-40de-952d-7ebe5f855925/image.png)

<br>

📚 이처럼 **프로미스는 비동기 처리 상태와 처리 결과를 관리하는 객체다.**

<br>

## 45.3 프로미스의 후속 처리 메서드

프로미스의 비동기 처리 상태가 변화하면 이에 따른 후속 처리를 해야 한다. 예를 들어, 프로미스가 `fulfilled` 상태가 되면 프로미스의 처리 결과를 가지고 무언가를 해야 하고, 프로미스가 `rejected` 상태가 되면 프로미스의 처리 결과(에러)를 가지고 에러 처리를 해야 한다. 이를 위해 프로미스는 후속 메서드 `then`, `catch`, `finally`를 제공한다.

프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출된다. 이때 후속 처리 메서드의 콜백 함수에 프로미스의 처리 결과가 인수로 전달된다.

모든 후속 처리 메서드는 프로미스를 반환하며, 비동기로 동작한다.

<br>

### 45.3.1 Promise.prototype.then

`then` 메서드는 두 개의 콜백 함수를 인수로 전달받는다.

- 첫 번째 콜백 함수는 프로미스가 `fulfilled` 상태(`resolve` 함수가 호출된 상태)가 되면 호출된다. 이때 콜백 함수는 프로미스의 비동기 처리 결과를 인수로 전달받는다.
- 두 번재 콜백 함수는 프로미스가 `rejected`된 상태(`reject` 함수가 호출된 상태)가 되면 호출된다. 이때 콜백 함수는 프로미스의 에러를 인수로 전달받는다.

즉, 쉽게 말해 첫 번째 콜백 함수는 비동기 처리가 성공했을 때 호출되는 성공 처리 콜백 함수이며, 두 번째 콜백 함수는 비동기 처리가 실패했을 때 호출되는 실패 처리 콜백 함수다.

<br>

#### 💻 예제 코드 11

```javascript
// fulfilled
new Promise((resolve) => resolve('fulfilled')).then(
  (v) => console.log(v),
  (e) => console.error(e)
); // fulfilled

// rejected
new Promise((_, reject) => reject(new Error('rejected'))).then(
  (v) => console.log(v),
  (e) => console.error(e)
); // Error: rejected
```

<br>

`then` 메서드는 언제나 프로미스를 반환한다. 만약 `then` 메서드의 콜백 함수가 프로미스를 반환하면 그 프로미스를 그대로 반환하고, 콜백 함수가 프로미스가 아닌 값을 반환하면(위 예제처럼) 그 값을 암묵적으로 `resolve` 또는 `reject` 하여 프로미스를 생성해 반환한다.

콜백 함수에는 반환값이 없지만, 즉 반환값이 `undefined`지만, `Promise.resolve(undefined)` 이런식으로 암묵적으로 프로미스로 감싸서 반환해준다.

<br>

### 45.3.2 Promise.prototype.catch

`catch` 메서드는 한 개의 콜백 함수를 인수로 전달받는다. `catch` 메서드의 콜백 함수는 프로미스가 `rejected` 상태인 경우만 호출된다.

<br>

#### 💻 예제 코드 12

```javascript
// rejected
new Promise((_, reject) => reject(new Error('rejected'))).catch((e) => console.log(e)); // Error: rejected
```

<br>

`catch` 메서드는 `then(undefined, onRejected)`과 동일하게 동작한다. 따라서 `then` 메서드와 마찬가지로 언제나 프로미스를 반환한다.

<br>

```javascript
// rejected
new Promise((_, reject) => reject(new Error('rejected'))).then(undefined, (e) => console.log(e)); // Error: rejected
```

<br>

### 45.3.3 Promise.prototype.finally

`finally` 메서드는 한 개의 콜백 함수를 인수로 전달받는다. `finally` 메서드의 콜백 함수는 프로미스의 성공(`fulfilled`) 또는 실패(`rejected`)와 상관없이 무조건 한 번 호출된다. `finally` 메서드는 프로미스의 상태와 상관없이 공통적으로 수행해야 할 처리 내용이 있을 때 유용하다. `finally` 메서드도 `then/catch` 메서드와 마찬가지로 언제나 프로미스를 반환한다.

<br>

#### 💻 예제 코드 13

<br>

```javascript
new Promise(() => {}).finally(() => console.log('finally')); // finally
```

<br>

프로미스로 구현한 비동기 함수 `promiseGet`을 사용해 후속 처리를 구현해보자.

<br>

#### 💻 `promiseGet` 함수의 후속 처리 예시

<br>

```javascript
// GET 요청을 위한 비동기 함수
const promiseGet = (url) => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
        // 성공적으로 응답을 전달받으면 resolve 함수를 호출한다.
        resolve(JSON.parse(xhr.response));
      } else {
        // 에러 처리를 위해 reject 함수를 호출한다.
        reject(new Error(xhr.status));
      }
    };
  });
};

// promiseGet 함수는 프로미스를 반환한다.
promiseGet('https://jsonplaceholder.typicode.com/posts/1')
  .then((res) => console.log(res))
  .catch((err) => console.error(err))
  .finally(() => console.log('Bye!'));
```

<br>

## 45.4 프로미스의 에러 처리

프로미스를 통해 비동기 함수 에러 처리를 문제 없이 처리할 수 있다. 비동기 처리에서 발생한 에러는 `then` 메서드의 두 번째 콜백 함수로 처리하거나 `catch`를 사용해 처리할 수도 있다.

<br>

#### 💻 then을 사용하여 에러 처리

```javascript
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 지정되었기 때문에 에러 발생
promiseGet(wrongUrl).then(
  (res) => console.log(res),
  (err) => console.error(err)
); // Error: 404
```

<br>

#### 💻 catch를 사용하여 에러 처리

```javascript
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 지정되었기 때문에 에러 발생
promiseGet(wrongUrl)
  .then((res) => console.log(res))
  .catch((err) => console.error(err)); // Error: 404
```

<br>

`then` 메서드를 사용하여 에러를 처리하면 첫 번째 콜백 함수에서 발생한 에러를 캐치하지 못하고 코드가 복잡하며 가독성이 좋지 않다는 단점이 있으므로 되도록, 아니 반드시 `catch` 메서드를 사용하여 모든 에러를 캐치하여 처리하도록 하는 것이 가독성을 높이고 에러 처리를 명확히 하도록 하자.

<br>

## 45.5 프로미스 체이닝

콜백 지옥, 콜백 헬을 해결하기 위해 프로미스는 프로미스 체이닝을 통해 보다 명확히 후속 처리를 가능케 한다.

<br>

#### 💻 프로미스 체이닝 예제 코드

<br>

```javascript
const url = 'https://jsonplaceholder.typicode.com';

// id가 1인 post의 userId를 취득
promiseGet(`${url}/posts/1`)
  // 취득한 post의 userId로 user 정보를 취득
  .then(({ userId }) => promiseGet(`${url}/users/${userId}`))
  .then((userInfo) => console.log(userInfo))
  .catch((err) => console.error(err));
```

<br>

이처럼 언제나 프로미스를 반환하는 `then`, `catch`, `finally` 후속 처리 메서드를 연속적으로 호출하는 것을 프로미스 체이닝이라 한다. 프로미스 체이닝을 사용하면 '예제 코드 6'와 비교해서 가독성이 훨씬 좋다.

하지만 프로미스도 콜백 패턴을 사용하므로 가독성 면에서는 좋지 않다. ES8에서 도입된 `async/await`을 사용하여 이 문제를 해결할 수 있다. `async/await`를 사용하면 프로미스의 후속 처리 메서드 없이 마치 동기 처리처럼 프로미스가 처리 결과를 반환하도록 구현할 수 있다.

<br>

#### `async/await` 예제 코드

<br>

```javascript
const url = 'https://jsonplaceholder.typicode.com';

(async () => {
  // id가 1인 post의 userId를 취득
  const { userId } = await promiseGet(`${url}/posts/1`);

  // 취득한 post의 userId로 user 정보를 취득
  const userInfo = await promiseGet(`${url}/users/${userId}`);

  console.log(userInfo);
})();
```

<br>

## 45.6 프로미스의 정적 메서드

### 45.6.1 Promise.resolve / Promise.reject

`Promise.resolve`와 `Promise.reject` 메서드는 이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용한다. (잘 사용 x, 책 참고)

### 45.6.2 Promise.all

`Promise.all` 메서드는 여러 개의 비동기 처리를 모두 병렬처리할 때 사용한다.

<br>

#### 💻 순차적 비동기 처리

<br>

```javascript
const requestData1 = () => new Promise((resolve) => setTimeout(() => resolve(1), 3000));
const requestData2 = () => new Promise((resolve) => setTimeout(() => resolve(2), 2000));
const requestData3 = () => new Promise((resolve) => setTimeout(() => resolve(3), 1000));

// 3개의 비동기 처리를 순차적으로 처리
const res = [];
requestData1()
  .then((data) => {
    res.push(data);
    return requestData2();
  })
  .then((data) => {
    res.push(data);
    return requestData3();
  })
  .then((data) => {
    res.push(data);
    console.log(res); // [1, 2, 3] => 약 6초 소요
  })
  .catch(console.error);
```

<br>

위 예제는 3개의 비동기 처리를 순차적으로 처리한다. 위 예제의 경우 서로 의존하지 않고 개별적으로 수행되므로 비동기 처리를 순차적으로 처리할 필요가 없다.

`Promise.all` 메서드는 여러 개의 비동기 처리를 모두 병렬 처리할 때 유용하다. 위 에제를 `Promise.all` 메서드를 사용해 병렬로 처리해보자.

<br>

#### 💻 Promise.all 사용 예제

<br>

```javascript
const requestData1 = () => new Promise((resolve) => setTimeout(() => resolve(1), 3000));
const requestData2 = () => new Promise((resolve) => setTimeout(() => resolve(2), 2000));
const requestData3 = () => new Promise((resolve) => setTimeout(() => resolve(3), 1000));

// 3개의 비동기 처리를 병렬로 처리
Promise.all([requestData1(), requestData2(), requestData3()])
  .then(console.log) // [1, 2, 3] => 약 3초 소요
  .catch(console.error);
```

<br>

`Promise.all` 메서드는 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받는다. 그리고 전달받은 모든 프로미스가 모두 `fulfilled` 상태가 되면 모든 처리 결과를 배열에 저장해 새로운 프로미스를 반환한다. 이때 전달된 배열의 순서대로 배열에 저장해 그 배열을 `resolve`하는 새로운 프로미스를 반환한다. 즉, 처리 순서를 보장한다.

`Promise.all` 메서드는 인수로 전달받은 배열의 프로미스가 하나라도 `rejected` 상태가 되면 나머지 프로미스가 `fulfilled` 상태가 되는 것을 기다리지 않고 즉시 종료한다.

`Promise.all` 메서드는 전달받은 이터러블의 요소가 프로미스가 아닌 경우 `Promise.resolve` 메서드를 통해 프로미스로 래핑한다.

<br>

```javascript
Promise.all([
  1, // Promise.resolve(1)
  2, // Promise.resolve(2)
  3, // Promise.resolve(3)
])
  .then(console.log) // [1, 2, 3]
  .catch(console.log);
```

<br>

### 45.6.3 Promise.race

`Promise.race` 메서드는 `Promise.all` 메서드와 동일하게 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받는다. `Promise.race` 메서드는 `Promise.all` 메서드처럼 모든 프로미스가 `fulfilled` 상태가 되는 것을 기다리는 것이 아니라 가장 먼저 `fulfilled` 상태가 된 프로미스의 처리 결과를 `resolve`하는 새로운 프로미스를 반환한다.

프로미스가 `rejected` 상태가 되면 `Promise.all` 메서드와 동일하게 처리된다. 하나라도 `rejected` 상태가 되면 에러를 `reject`하는 프로미스를 즉시 반환한다.

<br>

### 45.6.4 Promise.allSettled

`Promise.allSettled` 메서드는 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받는다. 그리고 전달받은 프로미스가 모두 `settled` 상태(비동기 처리가 수행된 상태)가 되면 처리 결고를 배열로 반환한다.

<br>

## 45.7 마이크로태스크 큐

<br>

#### 💻 예제 코드

```javascript
setTimeout(() => console.log(1), 0);

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3));
```

위 예제는 모두 비동기로 동작하므로 1 -> 2 -> 3 순으로 출력될 것 같지만 결과적으로 아래처럼 2 -> 3 -> 1 순으로 출력된다. 그 이유는 프로미스의 후속 처리 메서드의 콜백 함수는 태스크 큐가 아니라 마이크로태스크 큐에 저장되기 때문이다.

<br>

![](https://velog.velcdn.com/images/wlals4264/post/a6f9bcd2-d722-4160-9940-79cbe48dcbcb/image.png)

<br>

콜백 함수나 이벤트 핸들러를 일시 저장한다는 점에서 태스크 큐와 동일하지만 **마이크로태스크 큐는 태스크 큐보다 우선순위가 높다.** 즉, 이벤트 루프는 콜 스택이 비면 먼저 마이크로태스크 큐에서 대기하고 있는 함수를 가져와 실행한다. 이후 마이크로태스크 큐가 비면 태스크 큐에서 대기하고 있는 함수를 가져와 실행한다.

<br>

## 45.8 fetch

`fetch` 함수는 `XMLHttpRequest` 객체와 마찬가지로 HTTP 요청 전송 기능을 제공하는 클라이언트 사이드 Web API다. `XMLHttpRequest` 객체보다 사용법이 간단하고 프로미스를 지원하기 때문에 비동기 처리를 위한 콜백 패턴의 단점에서 자유롭다.

`fetch` 함수에는 HTTP 요청을 전송할 URL과 HTTP 요청 메서드, HTTP 요청 헤더, 페이로드 등을 설정한 객체를 전달한다.

<br>

```javascript
const promise = fetch(url [, options])
```

<br>

**`fetch` 함수는 HTTP 응답을 나타내는 `Response` 객체를 래핑한 `Promise` 객체를 반환한다.**

<br>

```javascript
fetch('https://jsonoplaceholder.typicode.com/todos/1').then((response) => console.log(response));
```

<br>

`fetch` 함수를 사용할 때는 에러 처리에 주의해야 한다. `fetch` 함수가 반환하는 프로미스는 기본적으로 `404 Not Found`나 `500 Internal Server Error`와 같은 HTTP 에러가 발생해도 에러를 `reject`하지 않고 불리언 타입의 `ok` 상태를 `false`로 설정한 `Response` 객체를 `resolve`한다. 오프라인 등의 네트워크 장애나 CORS 에러에 의해 요청이 완료되지 못한 경우에만 프로미스를 `reject`한다.

`axios`와 같은 라이브러리는 모든 HTTP 에러를 `reject`하는 프로미스를 반환하므로 모든 에러를 `catch`에서 처리할 수 있어 편리하다. 또한 인터셉터, 요청 설정 등 다양한 기능을 지원하므로 널리 사용된다. 👍🏻

<br>
<br>

```
> 출처 : 이웅모, 모던 자바스크립트 Deep Dive, 위키북스
```
